/**
 * @roboforge/codegen — firmware from a RobotProfile.
 *
 * The full generator will emit a complete PlatformIO project (main.cpp,
 * config.h, platformio.ini) and transpile the behavior. This first slice emits
 * `config.h`: the pin map + sensor table derived from the profile — exactly the
 * config the V1 pre-built runtime (firmware/roverlib) consumes.
 *
 * See docs/adr/0003-codegen-from-profile.md and 0006-firmware-build-strategy.md
 */

import type { RobotProfile } from '@roboforge/core';

export interface GeneratedFile {
  path: string;
  contents: string;
}

/** Emit a C++ header of `#define`s for every motor and sensor pin. */
export function generateConfigHeader(profile: RobotProfile): GeneratedFile {
  const lines: string[] = [
    '// AUTO-GENERATED by @roboforge/codegen — do not edit by hand.',
    `// Robot: ${profile.name} (${profile.id})`,
    '#pragma once',
    '',
    `#define RF_BOARD "${profile.board}"`,
    `#define RF_DRIVE_KIND "${profile.drive.kind}"`,
    `#define RF_DRIVER_CHIP "${profile.drive.driverChip}"`,
    '',
    '// ── Motor driver pins ──',
  ];

  for (const motor of profile.drive.motors) {
    for (const [role, pin] of Object.entries(motor.pins)) {
      lines.push(`#define RF_MOTOR_${ident(motor.id)}_${ident(role)} ${pin}`);
    }
  }

  lines.push('', '// ── Sensor pins ──');
  for (const sensor of profile.sensors) {
    lines.push(`// ${sensor.id}: ${sensor.driver}`);
    for (const [role, pin] of Object.entries(sensor.pins)) {
      lines.push(`#define RF_SENSOR_${ident(sensor.id)}_${ident(role)} ${pin}`);
    }
  }

  lines.push('');
  return { path: 'src/config.h', contents: lines.join('\n') };
}

function ident(s: string): string {
  return s.replace(/[^a-zA-Z0-9]+/g, '_').toUpperCase();
}
